[package]
name = "imguizmo-sys"
version = "0.0.1"
authors = ["Aaron Loucks <aloucks@cofront.net>"]
edition = "2018"

[dependencies]
imgui-sys = { git = "https://github.com/TrevTV/imgui-rs.git", features = [ "docking" ] }

[build-dependencies]
cc = "1"