[package]
name = "imguizmo-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.150"

[build-dependencies]
bindgen = "0.69.1"
cc = "1.0.83"
git2 = "0.18.1"
fs_extra = "1.3.0"