[package]
name = "imguizmo"
version = "0.0.1"
authors = ["Aaron Loucks <aloucks@cofront.net>"]
edition = "2018"

[dependencies]
imgui = "0.4"
imguizmo-sys = { version = "0.0.1", path = "../imguizmo-sys" }