[package]
name = "imguizmo"
version = "0.0.1"
authors = ["Aaron Loucks <aloucks@cofront.net>"]
edition = "2018"

[dependencies]
imgui = { git = "https://github.com/TrevTV/imgui-rs.git", features = [ "docking" ] }
imguizmo-sys = { version = "0.0.1", path = "../imguizmo-sys" }